### ISSUE TITLE
2-1 個人・法人向け情報発信ツールの提供　仮画像差し替え

### ISSUE THREAD

**Issue by astrakhan-web** [astrakhan-web/brainmarks#36]
・仮になってる画像を以下から探して差し替えください

https://drive.google.com/drive/u/0/folders/1n6lCf2j4Sb_nvZNXPrP-tYWdhqc13ciq

**Comment by JojoIshii** [comment]
見当たりません・・・

**Comment by astrakhan-web** [comment]
先方に確認します〜
